ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

SELECT CASE WHEN Z.USUINCLUSAO = 'AUTOMATICO' THEN 'AUTOMATICO' ELSE 'MANUAL' END TIPO_PED,
       COMPRADOR, COUNT(DISTINCT Z.NROPEDVENDA) QTD_PEDIDOS, SUM(ZI.QTDPEDIDA) QTD_UNI, SUM(ZI.QTDPEDIDA / ZI.QTDEMBALAGEM) QTD_CXS

  FROM MAD_PEDVENDA Z INNER JOIN MAD_PEDVENDAITEM ZI ON Z.NROPEDVENDA = ZI.NROPEDVENDA
                      INNER JOIN MAP_PRODUTO P ON P.SEQPRODUTO = ZI.SEQPRODUTO
                      INNER JOIN MAP_FAMDIVISAO F ON F.SEQFAMILIA = P.SEQFAMILIA
                      INNER JOIN MAX_COMPRADOR C ON C.SEQCOMPRADOR = F.SEQCOMPRADOR
                      
                                         
WHERE 1=1
  AND Z.NROEMPRESA IN (502,507,508)
  AND Z.DTAINCLUSAO >= DATE '2024-09-01'
  AND SITUACAOPED NOT IN ('C')
  AND Z.SEQPESSOA NOT IN (501,502,503,504,505,506,507,508)
  
  GROUP BY CASE WHEN Z.USUINCLUSAO = 'AUTOMATICO' THEN 'AUTOMATICO' ELSE 'MANUAL' END ,
           COMPRADOR
       
       ORDER BY 2
