-- Quantidade e Volume de Notas/Itens recebidos nas lojas por meio do AA - Abastecimento Automático - Sugestoes Mindset

WITH CTE_DTA AS (SELECT DATE '2024-09-01' DTA FROM DUAL)

SELECT /*+OPTIMIZER_FEATURES_ENABLE('19.1.0')*/
      'DIV AUTOMATICA' NF, COUNT(X.NUMERONF) QTD_NFS, SUM(XI.QUANTIDADE) QTD, SUM(XI.QUANTIDADE / QTDEMBALAGEM) QTD_CXS
  FROM MLF_NOTAFISCAL X INNER JOIN MLF_NFITEM XI ON X.SEQNF = XI.SEQNF
                        INNER JOIN CTE_DTA CTE ON X.DTAEMISSAO >= CTE.DTA

WHERE EXISTS (

SELECT 1 FROM MFL_DOCTOFISCAL A INNER JOIN MFL_DFITEM AI ON A.SEQNF = AI.SEQNF
                                INNER JOIN CTE_DTA CTE ON A.DTAMOVIMENTO >= CTE.DTA

WHERE A.NROPEDIDOVENDA IN (
SELECT Z.NROPEDVENDA FROM MAD_PEDVENDA Z INNER JOIN MAD_PEDVENDAITEM ZI ON Z.NROPEDVENDA = ZI.NROPEDVENDA
                                         INNER JOIN CTE_DTA CTE ON Z.DTAINCLUSAO >= CTE.DTA
                                         
WHERE 1=1
  AND Z.NROEMPRESA IN (502,507,508)
  AND Z.USUINCLUSAO = 'AUTOMATICO'
  AND SITUACAOPED = 'F'
  )
  
  AND A.NUMERODF = X.NUMERONF 
  AND A.SEQPESSOA = X.NROEMPRESA
  AND AI.SEQPRODUTO = XI.SEQPRODUTO
  AND A.NROEMPRESA = X.SEQPESSOA)
  
/* WITH CTE_DTA AS (SELECT DATE '2024-09-01' DTA FROM DUAL)


SELECT AI.QUANTIDADE, AI.QTDEMBALAGEM FROM MFL_DOCTOFISCAL A INNER JOIN MFL_DFITEM AI ON A.SEQNF = AI.SEQNF
                                INNER JOIN CTE_DTA CTE ON A.DTAMOVIMENTO >= CTE.DTA

WHERE A.NROPEDIDOVENDA IN (
SELECT Z.NROPEDVENDA FROM MAD_PEDVENDA Z INNER JOIN MAD_PEDVENDAITEM ZI ON Z.NROPEDVENDA = ZI.NROPEDVENDA
                                         INNER JOIN CTE_DTA CTE ON Z.DTAINCLUSAO >= CTE.DTA

WHERE 1=1
  AND Z.NROEMPRESA IN (502,507,508)
  AND Z.USUINCLUSAO = 'AUTOMATICO'
  AND SITUACAOPED = 'F'
  )
  AND A.NUMERODF = 42*/
