-- Analise Erro na Geração de Lote de Compras - Comprador EQUIPE FLV - Fornec 1389

-- SELECT * FROM CONSINCO.MAC_GERCOMPRAITEM X WHERE SEQGERCOMPRA = 263927

-- Descobre Empresa e Produto com erro no Insert

BEGIN
  FOR t IN (SELECT NROEMPRESA, SEQPRODUTO FROM MACV_INSCOMPRAITEM X WHERE X.SEQCOMPRADOR = 13 AND SEQFAMILIA  IN (
          SELECT SEQFAMILIA
          FROM MAP_FAMFORNEC
          WHERE MAP_FAMFORNEC.SEQFORNECEDOR IN (1389)) AND STATUSCOMPRA = 'A'
          
          ) 
  LOOP
    BEGIN
      INSERT INTO CONSINCO.MAC_GERCOMPRAITEM
      (
        SEQGERCOMPRA,
        SEQPRODUTO,
        NROEMPRESA,
        SEQFORNECEDOR,
        SITUACAOITEM,
        TFDTABASECUSTO,
        TFPERCNEGOC,
        QTDDIAABASTEC,
        DTAINICIOMEDVDA,
        DTAFINALMEDVDA,
        CONSIDERAATRASOFORNEC,
        CONSIDERASODIAUTIL,
        TIPOSUGCOMPRA,
        INDCOTACAO,
        GERARESERVALOTEPENDENTE,
        INDINATIVO,
        PZOMEDIOFORNEC,
        PZOMEDATRASOFORNEC,
        ESTQTERCEIRO,
        INDPRODFORASAZONAL,
        CENTRALLOJA
      )
      SELECT 
        '263927',
        SEQPRODUTO,
        MACV_INSCOMPRAITEM.NROEMPRESA,
        FORN.SEQFORNECEDOR,
        'R',
        NULL,
        NULL,
        '4',
        DATE '2023-08-16',
        SYSDATE,
        'N',
        'N',
        NULL,
        DECODE('C', 'F', 'S', NVL('N', 'N')),
        'N',
        DECODE(MACV_INSCOMPRAITEM.STATUSCOMPRA, 'A', 'N', 'S'),
        '0',
        '0',
        MACV_INSCOMPRAITEM.ESTQTERCEIRO,
        'N',
        'M'
      FROM 
        MACV_INSCOMPRAITEM,
        MAC_GERCOMPRAFORN FORN,
        MAX_EMPRESA E,
        MAF_FORNECDIVISAO F
      WHERE 
        FORN.SEQGERCOMPRA = '263927' AND
        E.NROEMPRESA = MACV_INSCOMPRAITEM.NROEMPRESA AND
        F.SEQFORNECEDOR = FORN.SEQFORNECEDOR AND
        F.NRODIVISAO = E.NRODIVISAO AND
        t.NROEMPRESA = MACV_INSCOMPRAITEM.NROEMPRESA AND
        t.seqproduto = MACV_INSCOMPRAITEM.seqproduto AND 
        MACV_INSCOMPRAITEM.NROEMPRESA IN (1, 2, 3, 4, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 501, 506) AND
        NOT EXISTS (
          SELECT 1
          FROM MAC_GERCOMPRAITEM X
          WHERE X.SEQGERCOMPRA = '263927' AND
            X.NROEMPRESA = MACV_INSCOMPRAITEM.NROEMPRESA AND
            X.SEQPRODUTO = MACV_INSCOMPRAITEM.SEQPRODUTO AND
            X.SEQFORNECEDOR = FORN.SEQFORNECEDOR
        ) AND
        MACV_INSCOMPRAITEM.SEQCOMPRADOR IN (13) AND
        MACV_INSCOMPRAITEM.SEQFAMILIA IN (
          SELECT SEQFAMILIA
          FROM MAP_FAMFORNEC
          WHERE MAP_FAMFORNEC.SEQFORNECEDOR IN (1389)
        ) AND
        MACV_INSCOMPRAITEM.STATUSCOMPRA = 'A' AND
        MACV_INSCOMPRAITEM.SEQFAMILIA IN (
          SELECT SEQFAMILIA
          FROM MAP_FAMDIVCATEG
          WHERE MAP_FAMDIVCATEG.SEQCATEGORIA IN (
            20003, 30688, 46156, 30758, 30900, 30789, 44116, 34637, 30735, 30790, 30676, 46359, 30791, 40273, 40272, 30738, 30675, 39858, 40054, 30908, 31515
          ) AND
          MAP_FAMDIVCATEG.STATUS = 'A' AND
          MAP_FAMDIVCATEG.NRODIVISAO = 1
        ) AND
        MACV_INSCOMPRAITEM.SEQFAMILIA NOT IN (
          SELECT SEQFAMILIA FROM MAP_FAMSAZON
        );
        
      EXCEPTION
        WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('Erro ao inserir para NROEMPRESA: ' || t.NROEMPRESA||' - Produto: '||T.Seqproduto);
    END;
  END LOOP;
END;
/
