ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

SELECT 'VIEW ORIGINAL' FONTE, H.NROEMPRESA, H.SEQPRODUTO, 
       LPAD(NVL(H.BASCALCICMSST,0) * 100, 8, '0')      BASCALCICMSST,                                                       
       LPAD(NVL(H.PERALIQUOTAICMSST,0) * 100, 4, '0')  PERALIQUOTAICMSST,                                                       
       LPAD(NVL(H.VLRICMSST,0) * 100, 8, '0')          VLRICMSST,                                                      
       LPAD(NVL(H.BASEFCPST,0) * 100, 8, '0')          BASEFCPST,                                                     
       LPAD(NVL(H.PERALIQFCPST,0) * 100, 4, '0')       PERALIQFCPST,                                                    
       LPAD(NVL(H.VLRFCPST,0) * 100, 8, '0')           VLRFCPST     
  FROM CONSINCO.MRL_NFCE_ENTRADA H WHERE SEQPRODUTO IN (253779,141031,592710,453974) AND NROEMPRESA = 36

 UNION ALL
 
SELECT NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL FROM DUAL

 UNION ALL

SELECT 'VIEW CUST' FONTE, NROEMPRESA, A.SEQPRODUTO, 
       LPAD(NVL((((DECODE(A.PRECOVALIDPROMOC, 0, A.PRECOVALIDNORMAL, A.PRECOVALIDPROMOC)) * (B.PERTRIBUTST/100)) * ((B.PERACRESCST/100 ) + 1)),0) * 100, 8, '0'),                                       
       LPAD(NVL(B.PERALIQUOTAST,0) * 100, 4, '0'),
       LPAD(NVL(((DECODE(A.PRECOVALIDPROMOC, 0, A.PRECOVALIDNORMAL, A.PRECOVALIDPROMOC) * (B.PERALIQUOTA/100)) * 100),0) * 100, 8, '0'),                                             
       LPAD(NVL(B.BASEFCPST,0) * 100, 8, '0'),
       LPAD(NVL(B.PERALIQFCPST,0) * 100, 4, '0'),  
       LPAD(NVL((DECODE(A.PRECOVALIDPROMOC, 0, A.PRECOVALIDNORMAL, A.PRECOVALIDPROMOC) * (B.PERALIQFCPST/100)),0) * 100, 8, '0')                                              
       
FROM CONSINCO.MRL_PRODEMPSEG A INNER JOIN MAP_PRODUTO P ON A.SEQPRODUTO = P.SEQPRODUTO
                               INNER JOIN MAP_FAMDIVISAO C ON C.SEQFAMILIA = P.SEQFAMILIA
                               INNER JOIN MAP_TRIBUTACAOUF B ON B.NROTRIBUTACAO = C.NROTRIBUTACAO AND B.UFEMPRESA = 'RJ' AND B.UFCLIENTEFORNEC = 'RJ' AND B.NROREGTRIBUTACAO = 0 AND B.TIPTRIBUTACAO = 'EI'
                                      
WHERE A.SEQPRODUTO = 141031 AND NROEMPRESA = 36 AND NROSEGMENTO = 3 AND QTDEMBALAGEM = 1 


