CREATE TABLE NAGT_BKP_DPTO_59 AS

SELECT X57.NRODEPARTAMENTO NROCERTO,
       X59.NRODEPARTAMENTO NROERRADO,
       X59.NROEMPRESA,
       X59.SEQPRODUTO
  FROM MRL_PRODUTOEMPRESA X59
       INNER JOIN MRL_PRODUTOEMPRESA X57
          ON X57.SEQPRODUTO = X59.SEQPRODUTO
         AND X57.NROEMPRESA = 57
 WHERE X59.NROEMPRESA = 59
   AND X59.NRODEPARTAMENTO != X57.NRODEPARTAMENTO;

BEGIN

   FOR dp IN (
       SELECT X57.NRODEPARTAMENTO NROCERTO,
              X59.NRODEPARTAMENTO NROERRADO,
              X59.NROEMPRESA,
              X59.SEQPRODUTO
         FROM MRL_PRODUTOEMPRESA X59
              INNER JOIN MRL_PRODUTOEMPRESA X57
                 ON X57.SEQPRODUTO = X59.SEQPRODUTO
                AND X57.NROEMPRESA = 57
        WHERE X59.NROEMPRESA = 59
          AND X59.NRODEPARTAMENTO != X57.NRODEPARTAMENTO
   )
   LOOP

      UPDATE MRL_PRODUTOEMPRESA X
         SET X.NRODEPARTAMENTO = dp.NROCERTO
       WHERE X.SEQPRODUTO = dp.SEQPRODUTO
         AND X.NROEMPRESA = dp.NROEMPRESA;

   END LOOP;

END;



