ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

-- Encontra carga no lock

SELECT B.IDSESSION, C.NROEMPRESA, 
  C.NOMEREDUZIDO, 
  B.CODUSUARIOROT,
  COUNT(1) QTDPEDIDO, 
  SUM(B.VALORPEDIDO) VALOR, 
        MIN(A.DTABASEFATURAMENTO) DATAINICIO, 
  MAX(A.DTABASEFATURAMENTO) DATAFIM, 
  B.CODREMESSA, A.SITUACAOPED, SUM(1) QTD_TOTAL 
FROM    MADV_PEDVENDAROTEIRIZACAO A, MAD_XROTEIRIZACAO B,
        MAX_EMPRESA C
WHERE   A.SITUACAOPED     =   'R'
AND     B.NROPEDVENDA     =   A.NROPEDVENDA
AND     C.NROEMPRESA      =   A.NROEMPRESA

GROUP   BY B.IDSESSION, 
  C.NROEMPRESA, 
  C.NOMEREDUZIDO, 
  B.CODUSUARIOROT, 
  B.CODREMESSA, SITUACAOPED
ORDER   BY B.IDSESSION, C.NROEMPRESA;

-- Encontra Ped Venda

SELECT  A.NROPEDVENDA 
FROM    MADV_PEDVENDAROTEIRIZACAO A, MAD_XROTEIRIZACAO B,
        MAX_EMPRESA C
WHERE   A.SITUACAOPED     =   'R'
AND     B.NROPEDVENDA     =   A.NROPEDVENDA
AND     C.NROEMPRESA      =   A.NROEMPRESA

-- Altera status do pedido de 'R' para 'S'

UPDATE MAD_PEDVENDA SET SITUACAOPED = 'S' WHERE NROPEDVENDA IN ();
COMMIT;

-- Deleta da tabela de roteirização

DELETE FROM MAD_XROTEIRIZACAO WHERE NROPEDVENDA IN ();
COMMIT;
SELECT * FROM MAD_XROTEIRIZACAO 
SELECT * FROM NAGT_ROTEIRIZACAOBACKUP


