ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

DECLARE
  I INTEGER := 0;
BEGIN
  FOR T IN (SELECT NROPEDVENDA
  FROM MAD_PEDVENDA X
 WHERE USUINCLUSAO = 'SREGINA'
   AND NROREPRESENTANTE = 503
   AND X.DTAINCLUSAO > SYSDATE - 1
   AND SITUACAOPED NOT IN ('D','C')) LOOP
   
    I := I + 1;
    UPDATE CONSINCO.MAD_PEDVENDAITEM B
       SET B.QTDATENDIDA = 0
     WHERE B.NROPEDVENDA = T.NROPEDVENDA;
  
    UPDATE CONSINCO.MAD_PEDVENDA
       SET SITUACAOPED     = 'C',
           DTACANCELAMENTO = SYSDATE,
           USUCANCELAMENTO = 'CANC_IMP',
           MOTCANCELAMENTO = 'Cancelamento devido a tabela incorreta',
           OBSCANCELAMENTO = 'MANUAL - GIULIANO',
           INDREPLICAFV    = 'S'
     WHERE NROPEDVENDA = T.NROPEDVENDA
       AND MAD_PEDVENDA.NROEMPRESA = 503;
  
    IF I = 100 THEN
      COMMIT;
      I := 0;
    END IF;
  END LOOP;
  COMMIT;
  
END;
