ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

SELECT Z.SEQFAMILIA, FAMILIA, C.SEQCATEGORIA, CAMINHOCOMPLETO, Z.USUARIOALTERACAO, STATUS
  FROM MAP_FAMDIVCATEG Z INNER JOIN MAP_CATEGORIA C ON C.SEQCATEGORIA = Z.SEQCATEGORIA
                         INNER JOIN MAP_FAMILIA F ON F.SEQFAMILIA = Z.SEQFAMILIA
      
     WHERE STATUS = 'A'
       AND C.SEQCATEGORIA NOT IN (20003,20004)
       AND EXISTS (
        
        SELECT 1
          FROM MAP_FAMDIVCATEG ZZ INNER JOIN MAP_CATEGORIA CC ON CC.SEQCATEGORIA = ZZ.SEQCATEGORIA
              
             WHERE STATUS = 'A'
               AND CC.SEQCATEGORIA IN (20003,20004)
               AND USUARIOALTERACAO = 'Consinco_API'
               AND ZZ.SEQFAMILIA = Z.SEQFAMILIA)
