-- Criando Backup - Consultas com a empresa 301 inclusas

CREATE TABLE CONSINCO.NAGT_MBI_TABCATRIBCONSULTA_BKP AS
SELECT * FROM CONSINCO.MBI_TABCATRIBCONSULTA WHERE VALORATRIBUTO = '301';

-- Deletando a empresa 301 das consultas

DELETE FROM CONSINCO.MBI_TABCATRIBCONSULTA WHERE VALORATRIBUTO = '301';

COMMIT;

-- Consultando

SELECT * FROM CONSINCO.MBI_TABCATRIBCONSULTA WHERE VALORATRIBUTO = '301'

