ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

-- Bkp

CREATE TABLE NAGV_TBKP_2422_2 AS

-- Corrige item a item, imposto a imposto
  
SELECT MAD_ADICAOITEM.NROADICAO,
       MAD_ADICAOITEM.NUMERODI,
       MAD_ADICAOITEM.SEQPRODUTO,
       MAD_ADICAOITEM.VLRII,
       MAD_ADICAOITEM.VLRIPI,
       MAD_ADICAOITEM.VLRPIS,
       MAD_ADICAOITEM.VLRCOFINS,
       MAD_ADICAOITEM.VLRICMS,
       MAD_ADICAOITEM.VLRAFRMM,
       MAD_ADICAOITEM.VLRFRETE,
       MAD_ADICAOITEM.VLRSEGURO,
       MAD_ADICAOITEM.VLRSISCOMEX,
       MAD_ADICAOITEM.VLRDESPAD
  FROM MAD_ADICAOITEM
 WHERE MAD_ADICAOITEM.NUMERODI = '2428245421'
       
 ORDER BY SEQPRODUTO;

-- Corrigem as Adicoes

BEGIN
  FOR t IN (SELECT I.NROADICAO,
       I.NUMERODI,
       SUM(I.VLRII) VLRII, SUM(I.VLRFRETE) FRETE, SUM(I.VLRIPI) IPI, SUM(I.VLRSEGURO) SEGURO, SUM(I.VLRPIS) PIS, SUM(I.VLRCOFINS) COFINS, SUM(I.VLRSISCOMEX) COMEX, SUM(I.VLRAFRMM) AFRMM, SUM(I.VLRICMS) ICMS
  FROM MAD_ADICAOITEM I
 WHERE I.NUMERODI = '2428245421'
 GROUP BY NUMERODI, NROADICAO
    )
    
    LOOP
      
    UPDATE MAD_ADICAO X SET X.VLRII = T.VLRII,    
                            X.VLRIPI = T.IPI,
                            X.VLRSEGURO = T.SEGURO,
                            X.VLRFRETE = T.FRETE,
                            X.VLRPIS = T.PIS,
                            X.VLRCOFINS = T.COFINS,
                            X.VLRSISCOMEX = T.COMEX,
                            X.VLRAFRMM = T.AFRMM,
                            X.VLRICMS = T.ICMS
                            
    WHERE X.NROADICAO = T.NROADICAO
      AND X.NUMERODI = T.NUMERODI;
      
    END LOOP;
    COMMIT;
    END;
