-- Corrige a NF jogando para a empresa correta

BEGIN
  FOR t IN (SELECT *
              FROM CONSINCO.NAGV_IMPNFEEMPINCORRETA X
             WHERE X.DTAEMISSAOC5 BETWEEN DATE '2024-07-05' AND SYSDATE + 1
               AND X.EMP_CERTA = 506)
    LOOP
      UPDATE CONSINCO.MRL_NFEIMPORTACAO I SET I.NROEMPRESA    = T.EMP_CERTA 
                                        WHERE I.SEQNOTAFISCAL = T.SEQNOTAFISCAL;
    END LOOP;
    
    COMMIT;
    
END;

-- Validação

SELECT *
  FROM CONSINCO.NAGV_IMPNFEEMPINCORRETA X
 WHERE X.DTAEMISSAOC5 BETWEEN DATE '2024-07-05' AND SYSDATE + 1
   AND X.EMP_CERTA = 506
