-- COrrecao Desconto Funrural Incorreto

BEGIN
  FOR tit IN (SELECT NROTITULO, ROUND(FVALORTOTALNF(N.ROWID, 'N') * 0.20 / 100,2) VLR_FUNRURAL_CORRETO, X.SEQTITULO
  FROM FI_TITULO X INNER JOIN MLF_NOTAFISCAL N ON N.LINKERP = X.LINKERP
 WHERE 1=1
   AND EXISTS (SELECT 1 FROM GE_PESSOA G WHERE G.INDPRODRURAL = 'S' AND G.SEQPESSOA = X.SEQPESSOA)
   AND ROUND(FVALORTOTALNF(N.ROWID, 'N') * 0.20 / 100,2) != (SELECT SUM(VLROPERACAO) FROM FI_TITOPERACAO O WHERE O.SEQTITULO = X.SEQTITULO AND O.CODOPERACAO = 29)
   AND NOT EXISTS (SELECT 1 FROM FI_TITOPERACAO OP WHERE OP.CODOPERACAO = 138 AND OP.SEQTITULO = X.SEQTITULO)
   AND N.DTAEMISSAO >= DATE '2024-01-01'
   AND CODESPECIE != 'BONIAC'
   AND X.NROEMPRESA IN (504,505))
   
   LOOP
     UPDATE FI_TITOPERACAO O SET O.VLROPERACAO = tit.vlr_funrural_correto,
                                 O.CODOPERACAO = 138,
                                 O.OBSERVACAO = 'Desconto Funrural'
                          WHERE CODOPERACAO = 29
                            AND O.SEQTITULO = tit.SEQTITULO;
   END LOOP;
   END;
