-- Procedure específica em
-- https://github.com/GiulianoGMS/Objects-Oracle/blob/main/NAGP_EXT_XML_DIA.prc

SELECT * FROM ALL_DIRECTORIES X WHERE DIRECTORY_NAME LIKE '%XML%';

DECLARE
  vSQL VARCHAR2(300);

BEGIN
  FOR t IN (SELECT LPAD(NROEMPRESA,3,0) EMP FROM MAX_EMPRESA WHERE NROEMPRESA NOT IN (1,2,3))
    LOOP
      vSQL := 'CREATE DIRECTORY EXT_XML_LOJA_'||t.EMP||' AS ''/u02/arquivos/xmls/files_store_'||t.EMP||'''';
    EXECUTE IMMEDIATE vSQL;
    END LOOP;
END;

BEGIN
  FOR emp IN (SELECT NROEMPRESA FROM MAX_EMPRESA X WHERE NROEMPRESA NOT IN (1,2,3,4,5,6) ORDER BY 1)
    LOOP
      NAGP_EXT_XML_DIA(DATE '2024-01-01', DATE '2025-07-31', emp.NROEMPRESA, 'N');
    END LOOP;
END;

SELECT * FROM NAGT_XML_EXTRAIDO X WHERE 1=1;
