-- Tabela DWNAGT_METAVENDA_NIVEIS_V2

SELECT * FROM DWNAGT_METAVENDA_NIVEIS_V2;

-- Temporária que vai subir os dados do csv

CREATE TABLE IMP_METAS
("DATA"                  VARCHAR2(100),
  NRO_EMPRESA            VARCHAR2(100),
  CATEGORIA_NIVEL_1,     VARCHAR2(100),
  CATEGORIA_NIVEL_2      VARCHAR2(100),      
  CATEGORIA_NIVEL_3      VARCHAR2(100),
 "META DE FATURAMENTO"   VARCHAR2(100),
 "META DE LUCRATIVIDADE" VARCHAR2(100),
 "META DE MARGEM"        VARCHAR2(100),
 "META DE PERDAS"        VARCHAR2(100),
  SEGMENTO               VARCHAR2(100)
 )
ORGANIZATION EXTERNAL
(
  TYPE ORACLE_LOADER
  DEFAULT DIRECTORY IMP_METAS
  ACCESS PARAMETERS 
  (
    RECORDS DELIMITED BY NEWLINE
    CHARACTERSET WE8MSWIN1252
    STRING SIZES ARE IN BYTES
    NOBADFILE
    NODISCARDFILE
    NOLOGFILE
    SKIP 1
    FIELDS TERMINATED BY ';' RTRIM
    REJECT ROWS WITH ALL NULL FIELDS
      ("DATA"                  CHAR,
        NRO_EMPRESA            CHAR,
        CATEGORIA_NIVEL_1      CHAR,
        CATEGORIA_NIVEL_2      CHAR,      
        CATEGORIA_NIVEL_3      CHAR,
       "META DE FATURAMENTO"   CHAR,
       "META DE LUCRATIVIDADE" CHAR,
       "META DE MARGEM"        CHAR,
       "META DE PERDAS"        CHAR,
        SEGMENTO               CHAR)
       )
  LOCATION (IMP_METAS:'metas.csv')
)
REJECT LIMIT UNLIMITED;

-- View com a formatação para o merge na proc

CREATE OR REPLACE VIEW IMPV_METAS AS

SELECT TO_DATE(X.DATA, 'DD/MM/YYYY') "DATA",
       TO_NUMBER(X.NRO_EMPRESA)       NRO_EMPRESA,
       CASE WHEN CATEGORIA_NIVEL_1 LIKE '%OUGUE' 
            THEN 'AÇOUGUE' 
            ELSE CATEGORIA_NIVEL_1 END CATEGORIA_NIVEL_1,
       X.CATEGORIA_NIVEL_2,
       X.CATEGORIA_NIVEL_3,
      CASE WHEN REGEXP_LIKE(TRIM(REPLACE("META DE FATURAMENTO", ',', '.')), '^[0-9]+(\.[0-9]+)?$')
           THEN TO_NUMBER(TRIM(REPLACE("META DE FATURAMENTO", ',', '.')))
           ELSE NULL END "META DE FATURAMENTO",
      CASE WHEN REGEXP_LIKE(TRIM(REPLACE("META DE LUCRATIVIDADE", ',', '.')), '^[0-9]+(\.[0-9]+)?$')
           THEN TO_NUMBER(TRIM(REPLACE("META DE LUCRATIVIDADE", ',', '.')))
           ELSE NULL END "META DE LUCRATIVIDADE",
      CASE WHEN REGEXP_LIKE(TRIM(REPLACE(REPLACE("META DE MARGEM", '%',''), ',', '.')), '^[0-9]+(\.[0-9]+)?$')
           THEN TO_NUMBER(TRIM(REPLACE(REPLACE("META DE MARGEM", '%',''), ',', '.')))
           ELSE NULL END "META DE MARGEM",
      CASE WHEN REGEXP_LIKE(TRIM(REPLACE(REPLACE(X."META DE PERDAS", '%',''), ',', '.')), '^[0-9]+(\.[0-9]+)?$')
           THEN TO_NUMBER(TRIM(REPLACE(REPLACE(X."META DE PERDAS", '%',''), ',', '.')))
           ELSE NULL END "META DE PERDAS",
       X.SEGMENTO 
 FROM IMP_METAS X

-- View

SELECT * FROM IMPV_METAS

-- Procedure

CREATE OR REPLACE PROCEDURE IMP_METAS_PROC AS

BEGIN
  
MERGE INTO DWNAGT_METAVENDA_NIVEIS_V2 tgt
USING IMPV_METAS src
   ON (tgt."DATA" = src."DATA" 
  AND  tgt.NRO_EMPRESA = src.NRO_EMPRESA
  AND  tgt.CATEGORIA_NIVEL_1 = src.CATEGORIA_NIVEL_1
  AND  tgt.CATEGORIA_NIVEL_2 = src.CATEGORIA_NIVEL_2
  AND  tgt.CATEGORIA_NIVEL_3 = src.CATEGORIA_NIVEL_3
  )
WHEN MATCHED THEN
  UPDATE SET
    tgt."META DE FATURAMENTO" = src."META DE FATURAMENTO",
    tgt."META DE LUCRATIVIDADE" = src."META DE LUCRATIVIDADE",
    tgt."META DE MARGEM" = src."META DE MARGEM",
    tgt."META DE PERDAS" = src."META DE PERDAS",
    tgt.SEGMENTO = src.SEGMENTO
WHEN NOT MATCHED THEN
  INSERT (
    "DATA",
    NRO_EMPRESA,
    CATEGORIA_NIVEL_1,
    CATEGORIA_NIVEL_2,
    CATEGORIA_NIVEL_3,
    "META DE FATURAMENTO",
    "META DE LUCRATIVIDADE",
    "META DE MARGEM",
    "META DE PERDAS",
    SEGMENTO
  )
  VALUES (
    src."DATA",
    src.NRO_EMPRESA,
    src.CATEGORIA_NIVEL_1,
    src.CATEGORIA_NIVEL_2,
    src.CATEGORIA_NIVEL_3,
    src."META DE FATURAMENTO",
    src."META DE LUCRATIVIDADE",
    src."META DE MARGEM",
    src."META DE PERDAS",
    src.SEGMENTO
  );
  
END IMP_METAS_PROC;

-- Chamada da Proc

BEGIN
  IMP_METAS_PROC;
  END;
  
-- Final

SELECT COUNT(1) FROM DWNAGT_METAVENDA_NIVEIS_V2
