SELECT *
  FROM NAGV_APP_METASVENDAS_MARCANAGUMO;
  
TRUNCATE TABLE DWNAGT_METAVENDA_NIVEIS_MARCANAGUMO;
  
CREATE TABLE IMP_METAS_TEMP_MP AS
  SELECT * FROM DWNAGT_METAVENDA_NIVEIS_MARCANAGUMO;
  
-- Tab que sobe os dados

CREATE TABLE IMP_METAS_MP
("DATA"                  VARCHAR2(100),
  NRO_EMPRESA            VARCHAR2(100),
  CATEGORIA_NIVEL_1      VARCHAR2(100),
  CATEGORIA_NIVEL_2      VARCHAR2(100),      
  CATEGORIA_NIVEL_3      VARCHAR2(100),
 "META DE FATURAMENTO"   VARCHAR2(100),
 "META DE LUCRATIVIDADE" VARCHAR2(100),
  SEGMENTO               VARCHAR2(100)
 )
ORGANIZATION EXTERNAL
(
  TYPE ORACLE_LOADER
  DEFAULT DIRECTORY IMP_METAS
  ACCESS PARAMETERS 
  (
    RECORDS DELIMITED BY NEWLINE
    CHARACTERSET WE8MSWIN1252
    STRING SIZES ARE IN BYTES
    NOBADFILE
    NODISCARDFILE
    NOLOGFILE
    SKIP 1
    FIELDS TERMINATED BY ';' RTRIM
    REJECT ROWS WITH ALL NULL FIELDS
      ("DATA"                  CHAR,
        NRO_EMPRESA            CHAR,
        CATEGORIA_NIVEL_1      CHAR,
        CATEGORIA_NIVEL_2      CHAR,      
        CATEGORIA_NIVEL_3      CHAR,
       "META DE FATURAMENTO"   CHAR,
       "META DE LUCRATIVIDADE" CHAR,
        SEGMENTO               CHAR)
       )
  LOCATION (IMP_METAS:'metas_mp.csv')
)
REJECT LIMIT UNLIMITED;

-- View com a formatação para o merge na proc

CREATE OR REPLACE VIEW IMPV_METAS_MP AS

SELECT "DATA", NRO_EMPRESA, CATEGORIA_NIVEL_1, CATEGORIA_NIVEL_2, CATEGORIA_NIVEL_3, "META DE FATURAMENTO", "META DE LUCRATIVIDADE",
        SEGMENTO

 FROM (

SELECT TO_DATE(TRIM(X.DATA), 'DD/MM/YYYY')"DATA",
       TO_NUMBER(X.NRO_EMPRESA)       NRO_EMPRESA,
       CASE WHEN CATEGORIA_NIVEL_1 LIKE '%OUGUE'
            THEN 'AÇOUGUE'
            ELSE CATEGORIA_NIVEL_1 END CATEGORIA_NIVEL_1,
       X.CATEGORIA_NIVEL_2,
       X.CATEGORIA_NIVEL_3,
      CASE WHEN REGEXP_LIKE(TRIM(REPLACE(REPLACE("META DE FATURAMENTO",'.',''), ',', '.')), '^[0-9]+(\.[0-9]+)?$')
           THEN TO_NUMBER(TRIM(REPLACE(REPLACE("META DE FATURAMENTO",'.',''), ',', '.')))
           ELSE 0 END "META DE FATURAMENTO",
      CASE WHEN REGEXP_LIKE(TRIM(REPLACE(REPLACE("META DE LUCRATIVIDADE",'.',''), ',', '.')), '^[0-9]+(\.[0-9]+)?$')
           THEN TO_NUMBER(TRIM(REPLACE(REPLACE("META DE LUCRATIVIDADE",'.',''), ',', '.')))
           ELSE 0 END "META DE LUCRATIVIDADE",
      
       X.SEGMENTO,
       ROW_NUMBER() OVER(PARTITION BY X.DATA, X.NRO_EMPRESA, X.CATEGORIA_NIVEL_1, X.CATEGORIA_NIVEL_2, X.CATEGORIA_NIVEL_3, X.SEGMENTO 
       ORDER BY X.DATA, X.NRO_EMPRESA, X.CATEGORIA_NIVEL_1, X.CATEGORIA_NIVEL_2, X.CATEGORIA_NIVEL_3, X.SEGMENTO)  ODR
       
 FROM IMP_METAS_MP X) XX
 
 WHERE 1=1;
 
 -- View para validacao de duplicidades
 
CREATE OR REPLACE VIEW IMPV_METAS_DUP_MP AS

SELECT "DATA", NRO_EMPRESA, CATEGORIA_NIVEL_1, CATEGORIA_NIVEL_2, CATEGORIA_NIVEL_3, "META DE FATURAMENTO", "META DE LUCRATIVIDADE",
        SEGMENTO

 FROM (

SELECT TO_DATE(TRIM(X.DATA), 'DD/MM/YYYY')"DATA",
       TO_NUMBER(X.NRO_EMPRESA)       NRO_EMPRESA,
       CASE WHEN CATEGORIA_NIVEL_1 LIKE '%OUGUE'
            THEN 'AÇOUGUE'
            ELSE CATEGORIA_NIVEL_1 END CATEGORIA_NIVEL_1,
       X.CATEGORIA_NIVEL_2,
       X.CATEGORIA_NIVEL_3,
      CASE WHEN REGEXP_LIKE(TRIM(REPLACE(REPLACE("META DE FATURAMENTO",'.',''), ',', '.')), '^[0-9]+(\.[0-9]+)?$')
           THEN TO_NUMBER(TRIM(REPLACE(REPLACE("META DE FATURAMENTO",'.',''), ',', '.')))
           ELSE 0 END "META DE FATURAMENTO",
      CASE WHEN REGEXP_LIKE(TRIM(REPLACE(REPLACE("META DE LUCRATIVIDADE",'.',''), ',', '.')), '^[0-9]+(\.[0-9]+)?$')
           THEN TO_NUMBER(TRIM(REPLACE(REPLACE("META DE LUCRATIVIDADE",'.',''), ',', '.')))
           ELSE 0 END "META DE LUCRATIVIDADE",
      
       X.SEGMENTO,
       ROW_NUMBER() OVER(PARTITION BY X.DATA, X.NRO_EMPRESA, X.CATEGORIA_NIVEL_1, X.CATEGORIA_NIVEL_2, X.CATEGORIA_NIVEL_3, X.SEGMENTO 
       ORDER BY X.DATA, X.NRO_EMPRESA, X.CATEGORIA_NIVEL_1, X.CATEGORIA_NIVEL_2, X.CATEGORIA_NIVEL_3, X.SEGMENTO)  ODR
       
 FROM IMP_METAS_MP X) XX
 
WHERE ODR > 1;

-- Procedure com Update

CREATE OR REPLACE PROCEDURE IMP_METAS_PROC_MP_UP AS

BEGIN

 DECLARE
 ctDup NUMBER(10);
 
 BEGIN

 DELETE FROM IMP_METAS_TEMP_MP WHERE 1=1;
 INSERT INTO IMP_METAS_TEMP_MP SELECT * FROM IMPV_METAS_MP;

 COMMIT;
 
 SELECT COUNT(1) 
   INTO ctDup
   FROM IMPV_METAS_DUP_MP;
   
 IF ctDup = 0 THEN
 
MERGE INTO DWNAGT_METAVENDA_NIVEIS_MARCANAGUMO tgt

USING IMP_METAS_TEMP_MP src
   ON (tgt."DATA" = src."DATA"
  AND  tgt.NRO_EMPRESA = src.NRO_EMPRESA
  AND  tgt.CATEGORIA_NIVEL_1 = src.CATEGORIA_NIVEL_1
  AND  tgt.CATEGORIA_NIVEL_2 = src.CATEGORIA_NIVEL_2
  AND  tgt.CATEGORIA_NIVEL_3 = src.CATEGORIA_NIVEL_3
  AND  tgt.SEGMENTO          = src.SEGMENTO
  )
WHEN MATCHED THEN
  UPDATE SET
    tgt."META DE FATURAMENTO" = src."META DE FATURAMENTO",
    tgt."META DE LUCRATIVIDADE" = src."META DE LUCRATIVIDADE"
 -- tgt."META DE MARGEM" = src."META DE MARGEM",
 -- tgt."META DE PERDAS" = src."META DE PERDAS"
    
    WHERE 
    
       tgt."META DE FATURAMENTO" != src."META DE FATURAMENTO"
    OR tgt."META DE LUCRATIVIDADE" != src."META DE LUCRATIVIDADE"
 -- OR tgt."META DE MARGEM" != src."META DE MARGEM"
 -- OR tgt."META DE PERDAS" != src."META DE PERDAS"

WHEN NOT MATCHED THEN

  INSERT (
    "DATA",
    NRO_EMPRESA,
    CATEGORIA_NIVEL_1,
    CATEGORIA_NIVEL_2,
    CATEGORIA_NIVEL_3,
    "META DE FATURAMENTO",
    "META DE LUCRATIVIDADE",
 -- "META DE MARGEM",
 -- "META DE PERDAS",
    SEGMENTO
  )
  VALUES (
    src."DATA",
    src.NRO_EMPRESA,
    src.CATEGORIA_NIVEL_1,
    src.CATEGORIA_NIVEL_2,
    src.CATEGORIA_NIVEL_3,
    src."META DE FATURAMENTO",
    src."META DE LUCRATIVIDADE",
 -- src."META DE MARGEM",
 -- src."META DE PERDAS",
    src.SEGMENTO
  );
 END IF;
  COMMIT;
 END;
END IMP_METAS_PROC_MP_UP;

-- Procedure para usuario sem update e validando duplicidades

CREATE OR REPLACE PROCEDURE IMP_METAS_PROC_MP (t IN NUMBER) AS

BEGIN

 DECLARE
 ctDup NUMBER(10);

BEGIN

 DELETE FROM IMP_METAS_TEMP_MP WHERE 1=1;
 INSERT INTO IMP_METAS_TEMP_MP SELECT * FROM IMPV_METAS_MP;

 COMMIT;
 
 SELECT COUNT(1) 
   INTO ctDup
   FROM IMPV_METAS_DUP_MP;
   
 IF ctDup = 0 THEN
 
MERGE INTO DWNAGT_METAVENDA_NIVEIS_MARCANAGUMO tgt

USING IMP_METAS_TEMP_MP src
   ON (tgt."DATA" = src."DATA"
  AND  tgt.NRO_EMPRESA = src.NRO_EMPRESA
  AND  tgt.CATEGORIA_NIVEL_1 = src.CATEGORIA_NIVEL_1
  AND  tgt.CATEGORIA_NIVEL_2 = src.CATEGORIA_NIVEL_2
  AND  tgt.CATEGORIA_NIVEL_3 = src.CATEGORIA_NIVEL_3
  AND  tgt.SEGMENTO          = src.SEGMENTO
  )

WHEN NOT MATCHED THEN

  INSERT (
    "DATA",
    NRO_EMPRESA,
    CATEGORIA_NIVEL_1,
    CATEGORIA_NIVEL_2,
    CATEGORIA_NIVEL_3,
    "META DE FATURAMENTO",
    "META DE LUCRATIVIDADE",
 -- "META DE MARGEM",
 -- "META DE PERDAS",
    SEGMENTO
  )
  VALUES (
    src."DATA",
    src.NRO_EMPRESA,
    src.CATEGORIA_NIVEL_1,
    src.CATEGORIA_NIVEL_2,
    src.CATEGORIA_NIVEL_3,
    src."META DE FATURAMENTO",
    src."META DE LUCRATIVIDADE",
 -- src."META DE MARGEM",
 -- src."META DE PERDAS",
    src.SEGMENTO
  );
  
  END IF;
  
  COMMIT;
 END;
END IMP_METAS_PROC_MP;

-- View em Nagumo

CREATE OR REPLACE VIEW IMPV_METAS_DUP_QVIEW_MP AS
SELECT LINHA, TO_CHAR("DATA",'DD/MM/YYYY') "DATA", NRO_EMPRESA, CATEGORIA_NIVEL_1, CATEGORIA_NIVEL_2, CATEGORIA_NIVEL_3,
       "META DE FATURAMENTO" AS "META DE FATURAMENTO",
       "META DE LUCRATIVIDADE" AS "META DE LUCRATIVIDADE",
        SEGMENTO

 FROM (

SELECT ROWNUM LINHA, TO_DATE(TRIM(X.DATA), 'DD/MM/YYYY')"DATA",
       TO_NUMBER(X.NRO_EMPRESA)       NRO_EMPRESA,
       CASE WHEN CATEGORIA_NIVEL_1 LIKE '%OUGUE'
            THEN 'AÇOUGUE'
            ELSE CATEGORIA_NIVEL_1 END CATEGORIA_NIVEL_1,
       X.CATEGORIA_NIVEL_2,
       X.CATEGORIA_NIVEL_3,
      "META DE FATURAMENTO" AS  "META DE FATURAMENTO",
      "META DE LUCRATIVIDADE" AS  "META DE LUCRATIVIDADE",

       X.SEGMENTO,
       ROW_NUMBER() OVER(PARTITION BY X.DATA, X.NRO_EMPRESA, X.CATEGORIA_NIVEL_1, X.CATEGORIA_NIVEL_2, X.CATEGORIA_NIVEL_3, X.SEGMENTO
       ORDER BY X.DATA, X.NRO_EMPRESA, X.CATEGORIA_NIVEL_1, X.CATEGORIA_NIVEL_2, X.CATEGORIA_NIVEL_3, X.SEGMENTO)  ODR

 FROM IMP_METAS_MP@BI X) XX

 WHERE ODR > 1

 ORDER BY 1;


