SELECT NAME, A.*
FROM ALL_PLSQL_OBJECT_SETTINGS A
WHERE A.name = 'PKG_CARREGAIMPOSTO'
AND OWNER = 'CONSINCO'

-- Compila sem Debug
  
ALTER PACKAGE CONSINCO.PKG_CARREGAIMPOSTO COMPILE;

-- Permissoes

GRANT DEBUG CONNECT SESSION TO C5ANALISTA;

REVOKE DEBUG CONNECT SESSION FROM C5ANALISTA;
