SELECT NAME, A.*
FROM ALL_PLSQL_OBJECT_SETTINGS A
WHERE A.name = 'PKG_CARREGAIMPOSTO'
AND OWNER = 'CONSINCO'

-- Compila sem Debug
  
ALTER PACKAGE CONSINCO.PKG_CARREGAIMPOSTO COMPILE;

-- Permissoes

GRANT DEBUG CONNECT SESSION TO C5ANALISTA;

REVOKE DEBUG CONNECT SESSION FROM C5ANALISTA;

-- Bkp

CREATE TABLE DBA_SYS_PRIVS_BKP AS

SELECT * FROM DBA_SYS_PRIVS WHERE GRANTEE = 'C5ANALISTA'

-- Removendo em loop

DECLARE
    
    vSQL VARCHAR2(100);

BEGIN
    FOR t IN (SELECT * 
                FROM DBA_SYS_PRIVS
               WHERE GRANTEE = 'C5ANALISTA'
                 AND PRIVILEGE LIKE '%DEBUG%')
               
    LOOP

    vSQL := 'REVOKE '||t.privilege||' FROM C5ANALISTA';
    
    EXECUTE IMMEDIATE vSQL;
    
    END LOOP;
    
    END;

-- Conferindo

SELECT * FROM DBA_SYS_PRIVS WHERE GRANTEE = 'C5ANALISTA'
