-- Erro na geração de evento CCe ou aguardando retorno
-- Altere STATUSCCE para 99, assim será possível reenviar o evento pela aplicação

SELECT MFL_NFECARTACORRECAO.SEQNFECARTA,
       MFL_NFECARTACORRECAO.SEQNOTAFISCAL,
       MFL_NFECARTACORRECAO.CORRECAO,
       MFL_NFECARTACORRECAO.NROCARTA,
       MFL_NFECARTACORRECAO.CODEVENTO,
       MFL_NFECARTACORRECAO.STATUSCCE, ROWID
  FROM MFL_NFECARTACORRECAO

 WHERE MFL_NFECARTACORRECAO.SEQNOTAFISCAL = '26856162' -- SeqNotaFiscal

 ORDER BY NROCARTA DESC
