SELECT DISTINCT INFO, CODRECEITA, RECEITARENDTO, QTDE
FROM (
    SELECT 'DESCRICAO RECEITA' AS INFO, SEQRECEITARENDTO AS CODRECEITA, RECEITARENDTO, NULL AS QTDE 
    FROM MRLV_COMPONENTESRECEITA X WHERE X.STATUSRECRENDTO = 'A' AND RECEITARENDTO LIKE UPPER('%'||'#LT1'||'%')

  UNION ALL

    SELECT 'PRODUTO FINAL', SEQRECEITARENDTO, X.SEQPRODUTOFINAL||' - '||X.PRODUTOFINAL, TO_CHAR(X.QTDUNIDPRODUZIDA)
    FROM MRLV_COMPONENTESRECEITA X WHERE X.STATUSRECRENDTO = 'A' AND EXISTS (SELECT SEQRECEITARENDTO FROM MRLV_COMPONENTESRECEITA XX 
                                                                              WHERE 1=1 AND XX.SEQRECEITARENDTO = X.SEQRECEITARENDTO AND XX.STATUSRECRENDTO = 'A' AND XX.RECEITARENDTO LIKE UPPER('%'||'#LT1'||'%'))

  UNION ALL

    SELECT 'COMPONENTE',SEQRECEITARENDTO, X.SEQPRODUTOCOMP||' - '||X.PRODUTOCOMP, TO_CHAR(X.QTDUTILIZADA,'FM999G999G990D900', 'NLS_NUMERIC_CHARACTERS='',.''')
    FROM MRLV_COMPONENTESRECEITA X WHERE X.STATUSRECRENDTO = 'A' AND EXISTS (SELECT SEQRECEITARENDTO FROM MRLV_COMPONENTESRECEITA XX 
                                                                              WHERE 1=1 AND XX.SEQRECEITARENDTO = X.SEQRECEITARENDTO AND XX.STATUSRECRENDTO = 'A' AND XX.RECEITARENDTO LIKE UPPER('%'||'#LT1'||'%'))
) SUB

ORDER BY CODRECEITA,
         CASE 
             WHEN INFO = 'DESCRICAO RECEITA' THEN 1
             WHEN INFO = 'PRODUTO FINAL' THEN 2
             WHEN INFO = 'COMPONENTE' THEN 3
             ELSE 4
         END;
