SELECT OWNER, TABLE_NAME
FROM ALL_TABLES@INFOPROCMSSQL;

SELECT A.TEXT
FROM ALL_VIEWS@INFOPROCMSSQL A;

SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH
  FROM ALL_TAB_COLUMNS@INFOPROCMSSQL A
 WHERE TABLE_NAME = 'RemarcaPromocoes';

SELECT TEXT
FROM ALL_VIEWS@INFOPROCMSSQL
WHERE VIEW_NAME = 'RemarcaPromocoes';

SELECT OWNER, TABLE_NAME, COLUMN_NAME 
FROM ALL_TAB_COLUMNS@INFOPROCMSSQL
WHERE COLUMN_NAME LIKE '%LOJA%'
