
SELECT DTAVDA, TO_CHAR(TRUNC(DTAHORLANCTO, 'HH') + INTERVAL '15' MINUTE * FLOOR(TO_NUMBER(TO_CHAR(DTAHORLANCTO, 'MI')) / 15), 'HH24:MI')||' - '||
       TO_CHAR((TRUNC(DTAHORLANCTO, 'HH') + INTERVAL '15' MINUTE * FLOOR(TO_NUMBER(TO_CHAR(DTAHORLANCTO, 'MI')) / 15) + '0.011'), 'HH24:MI')
       AS QUARTO_DE_HORA,
       NROEMPRESA, SUM(X.QTDITEM) QTDITEM, X.VLRITEM * SUM(X.QTDITEM) FATURAMENTO, COUNT(NRODOCTO) QTD_CUPONS
       
FROM MAXV_ABCDISTRIBBASE X

 WHERE X.NROEMPRESA = 37 AND X.DTAHORLANCTO > SYSDATE - 1 AND X.SEQPRODUTO = 5500
 
GROUP BY TRUNC(DTAHORLANCTO, 'HH') + INTERVAL '15' MINUTE * FLOOR(TO_NUMBER(TO_CHAR(DTAHORLANCTO, 'MI')) / 15),
      DTAVDA, NROEMPRESA, X.QTDITEM, X.VLRITEM
      
      ORDER BY TRUNC(DTAHORLANCTO, 'HH') + INTERVAL '15' MINUTE * FLOOR(TO_NUMBER(TO_CHAR(DTAHORLANCTO, 'MI')) / 15); 
      
