ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

CREATE TABLE NAGT_REMARCAPROMOCOES;

CREATE INDEX ipDTHRINICIO ON NAGT_REMARCAPROMOCOES (DTHRINICIO);
CREATE INDEX ipDTHRFIM    ON NAGT_REMARCAPROMOCOES (DTHRFIM);
CREATE INDEX ipCODPROD    ON NAGT_REMARCAPROMOCOES (CODIGOPRODUTO);

DROP INDEX ipCODPROD

SELECT * FROM consinco.NAGT_REMARCAPROMOCOES WHERE CODLOJA = 37
