DECLARE 
  vRowId VARCHAR2(100);

BEGIN
  SELECT MAX(Z.ROWID)
    INTO vRowId
      FROM MLF_NOTAFISCAL Z
     WHERE NUMERONF = 3886
           AND NROEMPRESA = 503;

  PKG_MAD_FATURAMENTO.SP_GERA_MRL_TITULOFIN(vRowId , 'E', 'I');

END;

-- Setar INDREPLICACAO = 'X'
-- Executar Shdl CAFD_INTEG_TIT_FINANCEIRO

SELECT * FROM MRL_TITULOFIN X WHERE X.NROTITULO = 3886 AND NROEMPRESA = 503
SELECT * FROM FI_TITULO X     WHERE X.NROTITULO = 3886 AND NROEMPRESA = 503


-- 
-- Select da Pkg de integracao :

SELECT *
  FROM MRL_TITULOFIN     A,
       MRL_PARAMETROFIN  B,
       MRL_EXPORTACAOFIN C,
       MAX_EMPRESA       D
 WHERE B.NROEMPRESA = NVL(A.NROEMPRESAFINANC, A.NROEMPRESA)
       AND A.NROEMPRESA = NVL(503, A.NROEMPRESA)
       AND D.NROEMPRESA = A.NROEMPRESA
       AND (NVL(D.INTRECCORPFINANCE, 'S') != 'E' OR
       ((NVL(D.INTRECCORPFINANCE, 'S') = 'E' AND
       A.ORIGEMDOC IN ('DEVC', 'FATU'))))
       AND A.INDEXPORTACAO IN ('I', 'C', 'A')
       AND A.OBRIGDIREITO = 'O'
       AND NVL(A.TIPOGERFINANC, 'T') = 'T'
       AND A.SEQTITULO = C.SEQTITULODEVOLUCAO(+)
       AND A.NROEMPRESA = C.NROEMPRESA(+)
       AND C.NROEMPRESA IS NULL
       AND A.VLRORIGINAL > 0
       AND (0 <= 0 OR (0 > 0 AND A.DTAEMISSAO >= TRUNC(SYSDATE) - 0))
 ORDER BY A.SEQTITULO
