ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

SELECT * FROM GE_LOGTROCAEMPRESA X 
 WHERE X.MODULO = 'MAXLOGPARAM'
   AND OBJETO IN ('frmCadParametro', 'frmDeposito')
   AND TRUNC(DATAHORAULTEXE) = TRUNC(SYSDATE) - 1
  
 ORDER BY DATAHORAULTEXE DESC
