CREATE OR REPLACE VIEW TMP_LOYALTYCOM_DOCTOSELO AS
SELECT * FROM MONITORPDV.TB_DOCTOSELO@LINK_C5 X;
CREATE PUBLIC SYNONYM TMP_LOYALTYCOM_DOCTOSELO FOR TMP_LOYALTYCOM_DOCTOSELO@CONSINCODW;

CREATE OR REPLACE VIEW TMP_LOYALTYCOM_DOCTOSELOTROCA AS
SELECT * FROM MONITORPDV.TB_DOCTOSELOTROCA@LINK_C5 X;
CREATE PUBLIC SYNONYM TMP_LOYALTYCOM_DOCTOSELOTROCA FOR TMP_LOYALTYCOM_DOCTOSELOTROCA@CONSINCODW;

CREATE OR REPLACE VIEW TMP_LOYALTYCOM_DOCTOSELOFAIXA AS
SELECT * FROM MONITORPDV.TB_DOCTOSELOFAIXA@LINK_C5 X;
CREATE PUBLIC SYNONYM TMP_LOYALTYCOM_DOCTOSELOFAIXA FOR TMP_LOYALTYCOM_DOCTOSELOFAIXA@CONSINCODW;
