CREATE OR REPLACE VIEW TMP_LOYALTYCOM_DOCTOSELO AS
SELECT * FROM MONITORPDV.TB_DOCTOSELO@LINK_C5 X;

CREATE OR REPLACE VIEW TMP_LOYALTYCOM_DOCTOSELOTROCA AS
SELECT * FROM MONITORPDV.TB_DOCTOSELOTROCA@LINK_C5 X;

CREATE OR REPLACE VIEW TMP_LOYALTYCOM_DOCTOSELOFAIXA AS
SELECT * FROM MONITORPDV.TB_DOCTOSELOFAIXA@LINK_C5 X;

Sinonimos em Producao | Nagumo

CREATE PUBLIC SYNONYM TMP_LOYALTYCOM_SELOS_ACE_REC  FOR LOYALTYCOM.TMP_LOYALTYCOM_SELOS_ACE_REC@CONSINCODW;
CREATE PUBLIC SYNONYM TMP_LOYALTYCOM_SELOS_TROCAS  FOR LOYALTYCOM.TMP_LOYALTYCOM_SELOS_TROCAS@CONSINCODW;
CREATE PUBLIC SYNONYM TMP_LOYALTYCOM_SELOS_FAIXA  FOR LOYALTYCOM.TMP_LOYALTYCOM_SELOS_FAIXA@CONSINCODW;

CREATE PUBLIC SYNONYM TMP_LOYALTYCOM_DOCTOSELO      FOR LOYALTYCOM.TMP_LOYALTYCOM_DOCTOSELO@CONSINCODW;
CREATE PUBLIC SYNONYM TMP_LOYALTYCOM_DOCTOSELOTROCA FOR LOYALTYCOM.TMP_LOYALTYCOM_DOCTOSELOTROCA@CONSINCODW;
CREATE PUBLIC SYNONYM TMP_LOYALTYCOM_DOCTOSELOFAIXA FOR LOYALTYCOM.TMP_LOYALTYCOM_DOCTOSELOFAIXA@CONSINCODW;
