SELECT * FROM CONSINCO.NAGT_BASE_56;

BEGIN
  FOR t IN (
SELECT A.SEQPRODUTO, C.QTDEMBALAGEM, C.CODACESSO, C.DATAHORAALTERACAO FROM NAGT_BASE_56 A INNER JOIN MAP_PRODCODIGO C ON C.SEQPRODUTO = A.SEQPRODUTO AND C.TIPCODIGO = 'D' AND NVL(C.INDUTILVENDA, 'N') = 'S' AND A.SEQPRODUTO = 108980
           )
  LOOP
    UPDATE MAP_PRODCODIGO C SET C.INDUTILVENDA = 'S',
                                C.USUARIOALTERACAO = 'MIX_BASE56',
                                C.DATAHORAALTERACAO = TRUNC(SYSDATE) - 3
                          WHERE C.SEQPRODUTO = T.SEQPRODUTO 
                            AND C.CODACESSO  = T.CODACESSO
                            AND C.QTDEMBALAGEM = T.QTDEMBALAGEM
                            AND C.TIPCODIGO = 'D';
  END LOOP;
END;

BEGIN
  FOR t IN (

SELECT DISTINCT B.STATUSVENDA STATUS_D, B1.STATUSVENDA STATUS_U, 
       A.SEQPRODUTO, B.NROEMPRESA, B.QTDEMBALAGEM, B.PRECOBASENORMAL, B.PRECOGERNORMAL, B.PRECOVALIDNORMAL, B.PRECOVALIDPROMOC, B1.PRECOVALIDNORMAL PRECO_UNIT, B1.PRECOVALIDNORMAL * B.QTDEMBALAGEM PRECO_NOVO
  FROM NAGT_BASE_56 A INNER JOIN MRL_PRODEMPSEG B ON B.SEQPRODUTO = A.SEQPRODUTO
                      INNER JOIN MAP_PRODCODIGO PC ON PC.SEQPRODUTO = A.SEQPRODUTO AND PC.QTDEMBALAGEM = B.QTDEMBALAGEM AND PC.TIPCODIGO = 'D'
                      INNER JOIN MRL_PRODEMPSEG B1 ON B1.SEQPRODUTO = B.SEQPRODUTO AND B1.NROEMPRESA = B.NROEMPRESA AND B1.NROSEGMENTO = B.NROSEGMENTO AND B1.QTDEMBALAGEM = 1 AND B1.PRECOVALIDNORMAL > 0
                      
 WHERE B.NROEMPRESA = 31
   AND (B.PRECOVALIDNORMAL = 0 OR B1.STATUSVENDA != 'A' OR B.STATUSVENDA != 'A')
   AND B.NROSEGMENTO = 4
   AND A.SEQPRODUTO = 108980
   --AND B.QTDEMBALAGEM > 1
    )
   
   LOOP
     UPDATE MRL_PRODEMPSEG G SET G.PRECOVALIDNORMAL = CASE WHEN G.PRECOVALIDNORMAL = 0 THEN G.PRECOVALIDNORMAL ELSE T.PRECO_NOVO END,
                                 G.PRECOBASENORMAL  = CASE WHEN G.PRECOVALIDNORMAL = 0 THEN G.PRECOVALIDNORMAL ELSE T.PRECO_NOVO END,
                                 G.PRECOGERNORMAL   = CASE WHEN G.PRECOVALIDNORMAL = 0 THEN G.PRECOVALIDNORMAL ELSE T.PRECO_NOVO END,
                                 G.STATUSVENDA = 'A'
     
                           WHERE G.QTDEMBALAGEM  = T.QTDEMBALAGEM
                             AND G.NROEMPRESA    = T.NROEMPRESA
                             AND G.SEQPRODUTO    = T.SEQPRODUTO
                             AND G.NROSEGMENTO   = 4;
    END LOOP;
    
END;
