/* Primeiro Loop para Ativar o "INDUTILVENDA' na MAP_PRODCODIGO */
BEGIN
  DECLARE vCount NUMBER := 0;
  BEGIN
  FOR atv IN (
SELECT A.SEQPRODUTO, C.QTDEMBALAGEM, C.CODACESSO, C.DATAHORAALTERACAO FROM NAGV_BASE_MIXDUN A INNER JOIN MAP_PRODCODIGO C ON C.SEQPRODUTO = A.SEQPRODUTO AND C.TIPCODIGO IN ('D','E') AND QTDEMBALAGEM > 1 AND NVL(C.INDUTILVENDA, 'N') != 'S'
           )
  LOOP
    UPDATE MAP_PRODCODIGO C SET C.INDUTILVENDA = 'S',
                                C.USUARIOALTERACAO = 'MIX_DUN',
                                C.DATAHORAALTERACAO = SYSDATE
                          WHERE C.SEQPRODUTO   = atv.SEQPRODUTO 
                            AND C.CODACESSO    = atv.CODACESSO
                            AND C.QTDEMBALAGEM = atv.QTDEMBALAGEM
                            AND C.TIPCODIGO IN ('E','D');
                            vCount := vCount + 1;
  END LOOP;
  DBMS_OUTPUT.put_line('Total Atualizado: '||vCount);
  
  END;
END;

/* Segundo Loop para replicar o preço do unitário para a embalagem >1, ou alterar o status de venda para 'A' da embalagem > 1 */

BEGIN
  FOR rep IN (

SELECT DISTINCT B.STATUSVENDA STATUS_D, B1.STATUSVENDA STATUS_U, 
       A.SEQPRODUTO, B.NROEMPRESA, B.QTDEMBALAGEM, B.PRECOBASENORMAL, B.PRECOGERNORMAL, B.PRECOVALIDNORMAL, B.PRECOVALIDPROMOC, B1.PRECOVALIDNORMAL PRECO_UNIT, B1.PRECOVALIDNORMAL * B.QTDEMBALAGEM PRECO_NOVO
  FROM NAGV_BASE_MIXDUN A INNER JOIN MRL_PRODEMPSEG B ON B.SEQPRODUTO = A.SEQPRODUTO
                          INNER JOIN MAP_PRODCODIGO PC ON PC.SEQPRODUTO = A.SEQPRODUTO AND PC.QTDEMBALAGEM = B.QTDEMBALAGEM AND PC.TIPCODIGO IN ('D','E')
                          INNER JOIN MRL_PRODEMPSEG B1 ON B1.SEQPRODUTO = B.SEQPRODUTO AND B1.NROEMPRESA = B.NROEMPRESA AND B1.NROSEGMENTO = B.NROSEGMENTO AND B1.QTDEMBALAGEM = 1 AND B1.PRECOVALIDNORMAL > 0 AND B1.STATUSVENDA = 'A'
                      
 WHERE B.NROEMPRESA IN (31,41)
   AND (B.PRECOVALIDNORMAL = 0 OR B1.STATUSVENDA != 'A' OR B.STATUSVENDA != 'A' OR B1.PRECOVALIDNORMAL * B.QTDEMBALAGEM != B1.PRECOVALIDNORMAL)
   AND B.NROSEGMENTO = 4
    )
   
   LOOP
     UPDATE MRL_PRODEMPSEG G SET G.PRECOVALIDNORMAL = rep.PRECO_NOVO,
                                 G.PRECOBASENORMAL  = rep.PRECO_NOVO,
                                 G.PRECOGERNORMAL   = rep.PRECO_NOVO,
                                 G.STATUSVENDA = 'A'
     
                           WHERE G.QTDEMBALAGEM  = rep.QTDEMBALAGEM
                             AND G.NROEMPRESA    = rep.NROEMPRESA
                             AND G.SEQPRODUTO    = rep.SEQPRODUTO
                             AND G.NROSEGMENTO   = 4;
    END LOOP;
    
END;

SELECT * FROM MAP_PRODCODIGO Z WHERE Z.USUARIOALTERACAO = 'MIX_DUN'
   
   
