SELECT OWNER, OBJECT_TYPE, OBJECT_NAME, OBJECT_DEFINITION
  FROM (
        /* VIEWS */
        SELECT V.TABLE_SCHEMA  OWNER,
                'VIEW'  OBJECT_TYPE,
                V.TABLE_NAME   OBJECT_NAME,
                V.VIEW_DEFINITION  OBJECT_DEFINITION
          FROM INFORMATION_SCHEMA.VIEWS V
        
        UNION ALL
        
        /* PROCEDURES e FUNCTIONS */
        SELECT R.ROUTINE_SCHEMA       OWNER,
                R.ROUTINE_TYPE        OBJECT_TYPE,
                R.ROUTINE_NAME        OBJECT_NAME,
                R.ROUTINE_DEFINITION  OBJECT_DEFINITION
          FROM INFORMATION_SCHEMA.ROUTINES R
        
        UNION ALL
        
        /* TRIGGERS */
        SELECT T.TRIGGER_SCHEMA  OWNER,
                'TRIGGER'        OBJECT_TYPE,
                T.TRIGGER_NAME   OBJECT_NAME,
                T.ACTION_STATEMENT  OBJECT_DEFINITION
          FROM INFORMATION_SCHEMA.TRIGGERS T) X
 WHERE UPPER(X.OBJECT_DEFINITION) LIKE '%INSERT INTO%';
