CREATE OR REPLACE VIEW NAGV_BASE_MIXDUN AS
SELECT DISTINCT P.SEQPRODUTO, CATEGORIAN1, CATEGORIAN2, CATEGORIAN3, CATEGORIAN4, CATEGORIAN5

  FROM MAP_PRODUTO P INNER JOIN DIM_CATEGORIA@CONSINCODW C ON C.SEQFAMILIA = P.SEQFAMILIA
                     INNER JOIN MAP_PRODCODIGO PC ON PC.SEQPRODUTO = P.SEQPRODUTO AND PC.TIPCODIGO = 'D'
 WHERE
                       CATEGORIAN1 = 'COMMODITIES'
                  AND  CATEGORIAN2 = 'COMMODITIES'
                  AND (CATEGORIAN3 = 'OLEO'      AND CATEGORIAN5 =   'TRADICIONAL'
                   OR  CATEGORIAN3 = 'ARROZ'     AND CATEGORIAN4 IN ('BRANCO', 'PARBOLIZADO')
                   OR  CATEGORIAN3 = 'LEITE UHT' AND CATEGORIAN4 IN ('INTEGRAL', 'SEMI DESNATADO','ZERO LACTOSE','DESNATADO')
                   OR  CATEGORIAN3 = 'FEIJAO'    AND CATEGORIAN4 IN ('CARIOCA','PRETO'))

                   OR  CATEGORIAN1 = 'BASICOS E MATINAIS'
                  AND (CATEGORIAN2 = 'COMMODITIES'
                  AND (CATEGORIAN3 = 'ACUCAR'    AND CATEGORIAN4 IN ('CRISTAL','REFINADO')
                   OR  CATEGORIAN3 = 'CAFE'      AND CATEGORIAN4 =   'TORRADO E MOIDO' AND CATEGORIAN5 = 'TRADICIONAL')
                   OR  CATEGORIAN2 = 'MATINAIS'
                  AND  CATEGORIAN3 = 'BEBIDA PRONTA LACTEA' AND CATEGORIAN5 LIKE 'IN_IVIDUAL')

                   OR  CATEGORIAN1 = 'MERCEARIA SALGADA'
                  AND  CATEGORIAN2 = 'TEMPEROS E CALDOS'
                  AND  CATEGORIAN3 = 'SAL'       AND CATEGORIAN4 IN ('GROSSO','REFINADO')

                   OR  CATEGORIAN1 = 'MERCEARIA DOCE'
                  AND  CATEGORIAN2 = 'DOCE'
                  AND  CATEGORIAN3 = 'BISCOITO ' AND CATEGORIAN4 IN ('CRACKER','MAISENA','WAFER')

                   OR  CATEGORIAN1 = 'BEBIDAS'
                  AND (CATEGORIAN2 = 'ALCOOLICAS'
                  AND (CATEGORIAN3 = 'AGUARDENTE'AND CATEGORIAN4 IN ('GOLD','TRADICIONAL')
                   OR  CATEGORIAN3 = 'CERVEJA'   AND CATEGORIAN5 =   'LATA'))
                   OR  CATEGORIAN2 = 'NAO ALCOOLICAS'
                  AND (CATEGORIAN3 = 'BEBIDA FRUTA'
                                                 AND CATEGORIAN4 =   'ADOCADA' AND CATEGORIAN5 = 'INDIVIDUAL'
                   OR  CATEGORIAN3 = 'REFRIGERANTE'
                                                 AND CATEGORIAN4 IN ('LATA','PET')
                   OR  CATEGORIAN3 = 'AGUA MINERAL')

ORDER BY 1;
