ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

SELECT DISTINCT B.STATUS, X.SEQPROMOCAO, X.NROEMPRESA, PROMOCAO, DTAINICIO, DTAFIM, DTAINICIOPROM, DTAFIMPROM, SEQPRODUTO
  FROM MRL_PROMOCAO X INNER JOIN MRL_PROMOCAOITEM B ON B.SEQPROMOCAO = X.SEQPROMOCAO AND X.NROEMPRESA = B.NROEMPRESA
 WHERE X.NROEMPRESA = 57
   AND (TRUNC(SYSDATE) BETWEEN DTAINICIO AND DTAFIM AND DTAFIM <= DATE '2024-09-04'    
   OR  TRUNC(SYSDATE) BETWEEN B.DTAINICIOPROM AND B.DTAFIMPROM AND DTAFIMPROM <= DATE '2024-09-04')
   AND STATUS = 'A'
