-- Ticket 626184

CREATE TABLE NAGT_BASE_PROD_CONSUMO_EMB (SEQPRODUTO NUMBER);

SELECT * FROM NAGT_BASE_PROD_CONSUMO_EMB;

SELECT /*+ ORDERED */ XI.SEQPRODUTO, 
       LISTAGG(DISTINCT X.CODGERALOPER, ', ') WITHIN GROUP (ORDER BY XI.SEQPRODUTO) CGOS
       
  FROM MLF_NFITEM XI INNER JOIN NAGT_BASE_PROD_CONSUMO_EMB B ON B.SEQPRODUTO = XI.SEQPRODUTO
                     INNER JOIN MLF_NOTAFISCAL X ON X.SEQNF = XI.SEQNF   
 
WHERE 1=1
  AND X.DTAHORLANCTO >= SYSDATE - 365
  
  GROUP BY XI.SEQPRODUTO
  
  UNION ALL
  
SELECT  /*+ ORDERED */ AI.SEQPRODUTO, 
       LISTAGG(DISTINCT A.CGO, ', ') WITHIN GROUP (ORDER BY AI.SEQPRODUTO) CGOS
  FROM OR_NFDESPESA A INNER JOIN OR_NFITENSDESPESA AI ON AI.SEQNOTA = A.SEQNOTA
                      INNER JOIN NAGT_BASE_PROD_CONSUMO_EMB C ON C.SEQPRODUTO = AI.SEQPRODUTO
                      
WHERE 1=1
  AND A.DTAENTRADA >= SYSDATE - 365
  
  GROUP BY AI.SEQPRODUTO
  
