SELECT X.SEQPRODUTO, DESCCOMPLETA, NROEMPRESA, X.CMULTCUSLIQUIDOEMP, X.CMULTVLRNF 

  FROM CONSINCO.MRL_PRODUTOEMPRESA X INNER JOIN CONSINCO.MAP_PRODUTO P ON X.SEQPRODUTO = P.SEQPRODUTO

 WHERE (X.CMULTCUSLIQUIDOEMP > 999 OR CMULTVLRNF > 999)
   AND EXISTS (SELECT 1 FROM CONSINCO.MRLV_COMPONENTESRECEITA A WHERE A.SEQPRODUTOFINAL = X.SEQPRODUTO
                                                                   OR A.SEQPRODUTOCOMP  = X.SEQPRODUTO)
                                                                   
                                                                   ORDER BY 2
