-- Lembrar de validar o segmento

INSERT INTO MAD_PRODLOGPRECO
  (SEQLOGPRECO,
   NROEMPRESA,
   CENTRALLOJA,
   SEQPRODUTO,
   QTDEMBALAGEM,
   NROSEGMENTO,
   PRECO,
   FAIXAACRFINANCEIRO,
   DTAHORALTERACAO,
   INDGERAPRECO,
   USUALTERACAO,
   PROCESSOALTERACAO,
   APROVADOREPROVADO,
   DTAHORAPROVREPROV,
   USUAPROVREPROV,
   TIPOALTPRECO,
   MOTIVOALTMANUAL,
   DTAPROGALTERACAO,
   INDGERAPRODBASE,
   INDGERAPRODSIMILAR,
   INDREPLICACAO,
   INDGEROUREPLICACAO,
   CLASSIFCOMERCABC,
   ORIGEM)
   SELECT NULL,
         X.NROEMPRESA,
         E.INDCENTRALLOJA,
         X.SEQPRODUTO,
         X.QTDEMBALAGEM,
         X.NROSEGMENTO,
         FPRECOEMBPRODEMPSEG(X.SEQPRODUTO,
                             1,
                             X.NROSEGMENTO,
                             X.NROEMPRESA,
                             'B') * X.QTDEMBALAGEM,
         'A',
         SYSDATE,
         'V',
         'AUTOMATICO',
         'M',
         'A',
         SYSDATE,
         'AUTOMATICO',
         'N',
         ' Script Correção Preço de Embalagens',
         TRUNC(SYSDATE),
         'N',
         'N',
         'S',
         NULL,
         NULL,
         'E'
    FROM MRL_PRODEMPSEG X
   INNER JOIN MAP_PRODUTO P
      ON (P.SEQPRODUTO = X.SEQPRODUTO)
   
   INNER JOIN MAX_EMPRESA E
      ON (E.NROEMPRESA = X.NROEMPRESA)
   INNER JOIN MRL_PRODUTOEMPRESA Z
      ON (Z.SEQPRODUTO = X.SEQPRODUTO AND Z.NROEMPRESA = X.NROEMPRESA)
   WHERE X.NROSEGMENTO IN (2)
        -- AND X.STATUSVENDA = 'A'
         AND X.QTDEMBALAGEM > 1
         AND (X.PRECOVALIDNORMAL / X.QTDEMBALAGEM) <> 0
         AND EXISTS (SELECT 1
            FROM MRL_PRODEMPSEG Z
           WHERE Z.SEQPRODUTO = X.SEQPRODUTO
                 AND Z.NROEMPRESA = X.NROEMPRESA
                 AND Z.QTDEMBALAGEM > 1
                 AND X.NROSEGMENTO = Z.NROSEGMENTO
                 AND Z.STATUSVENDA = X.STATUSVENDA)
/*                 AND Z.SEQPRODUTO = 25614
*/                 AND Z.NROEMPRESA = 58
         AND EXISTS
   (SELECT 1
            FROM MRL_PRODEMPSEG Y
           WHERE X.SEQPRODUTO = Y.SEQPRODUTO
                 AND X.STATUSVENDA = Y.STATUSVENDA
                 AND X.NROSEGMENTO = Y.NROSEGMENTO
                 AND Y.QTDEMBALAGEM = 1
                 AND X.NROEMPRESA = Y.NROEMPRESA
                 AND ROUND((X.PRECOVALIDNORMAL / X.QTDEMBALAGEM), 2) <>
                 ROUND((Y.PRECOVALIDNORMAL / Y.QTDEMBALAGEM), 2));
                 
-- Conferindo

SELECT NROEMPRESA, SEQPRODUTO, NROSEGMENTO, QTDEMBALAGEM, PRECOVALIDNORMAL, PRECOVALIDNORMAL / QTDEMBALAGEM PRECO_UNI_EMB, STATUSVENDA
  FROM MRL_PRODEMPSEG A 
 WHERE 1=1
   AND NROEMPRESA  = 58
   AND NROSEGMENTO = 2
   AND MOTIVOPRECOGERADO = 'Equiparação'
   AND EXISTS(
 
SELECT 1
  FROM MRL_PRODEMPSEG X 
 WHERE NROEMPRESA  = A.NROEMPRESA
   AND NROSEGMENTO = A.NROSEGMENTO
   AND MOTIVOPRECOGERADO = 'Equiparação'
   AND QTDEMBALAGEM = 1
   AND EXISTS (SELECT 2
                FROM MRL_PRODEMPSEG Z 
               WHERE NROEMPRESA  = X.NROEMPRESA
                 AND NROSEGMENTO = X.NROSEGMENTO
                 AND MOTIVOPRECOGERADO = 'Equiparação'
                 AND Z.SEQPRODUTO = X.SEQPRODUTO
                 AND Z.QTDEMBALAGEM != X.QTDEMBALAGEM
                 AND ROUND(Z.PRECOVALIDNORMAL / Z.QTDEMBALAGEM,2) != X.PRECOVALIDNORMAL
                 )
                
   --AND X.SEQPRODUTO = 212234
   AND X.SEQPRODUTO = A.SEQPRODUTO)
