ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

-- Replica Especie de End nos Produtos - WMS

UPDATE CONSINCO.MRL_PRODEMPRESAWM A
   SET CODTIPENDERECO = 'N'
 WHERE A.NROEMPRESA = '502'
       AND NVL(CODTIPENDERECO, 'x') = 'x'
       AND A.NROEMPRESA = 502;

INSERT INTO CONSINCO.MAD_PRODESPENDERECO (

SELECT DISTINCT B.SEQPRODUTO,
       502,
       B.CODESPECENDERECO,
       B.QTDEMBALAGEM,
       B.PALETELASTRO,
       B.PALETEALTURA,
       B.ESTQMINREPOSICAO,
       B.USUARIOALTERACAO,
       B.INDALTEROUAPP
  FROM CONSINCO.MAD_PRODESPENDERECO B
 WHERE 1=1
       AND NROEMPRESA = '503'
       AND CODESPECENDERECO IN ('A', 'P'));
           
       COMMIT;
        
