BEGIN
  FOR usu IN (SELECT SEQUSUARIO, CODUSUARIO FROM GE_USUARIO X WHERE CODUSUARIO IN ('DNSILVA','GOSOUZA','DISILVA'))
    LOOP
      FOR emp IN (SELECT 'ARMAZ_PRAZO_RESTRITO' TIPO, usu.SEQUSUARIO, NROEMPRESA
                    FROM MAX_EMPRESA X 
                   WHERE NROEMPRESA IN (501,502,503,506,507,508) 
                     AND NOT EXISTS (SELECT 1 FROM MLO_PERMESPECIALUSER A WHERE A.SEQUSUARIO = usu.SEQUSUARIO AND A.NROEMPRESA = X.NROEMPRESA))
        
      LOOP
        
      INSERT INTO MLO_PERMESPECIALUSER A VALUES (emp.TIPO, emp.SEQUSUARIO, emp.NROEMPRESA);
      END LOOP;
    END LOOP;
    
END;
  
