CREATE OR REPLACE VIEW CONSINCO.NAGV_COLETORES AS

SELECT SID, INST_ID, SERIAL#, USERNAME, STATUS, OSUSER, LOGON_TIME, CASE WHEN OSUSER LIKE '%Lojas%' THEN 'LJ' ELSE 'CD' END CIL, CLIENT_IDENTIFIER
  FROM GV$SESSION X 
 WHERE 1=1
  AND OSUSER LIKE '%Coletor%'
  
  ORDER BY LOGON_TIME ASC; 
  
BEGIN
  FOR t IN (SELECT * FROM NAGV_COLETORES
             WHERE 1=1
               AND OSUSER LIKE '%Coletor%'
               AND CLIENT_IDENTIFIER = 'GIGOMES'
             ORDER BY LOGON_TIME ASC)
  LOOP
    BEGIN
      EXECUTE IMMEDIATE 'ALTER SYSTEM DISCONNECT SESSION '''||t.SID||', '||t.SERIAL#||', @'||t.INST_ID||''' POST_TRANSACTION';
    EXCEPTION
      WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERRO ao desconectar sessão: ' || t.SID);
    END;
  END LOOP;
END;

SELECT * FROM NAGV_COLETORES
