-- Altera o STATUSNFE das notas que foram emitidas durante compilamento da pkg de faturamento
-- e que tiveram falha no retorno, porem foram autorizadas

BEGIN
  FOR t IN (
    
SELECT DISTINCT MFL_NFELOG.SEQNOTAFISCAL, MLFV_BASENFE.NUMERONF
              FROM MFL_NFELOG, MLFV_BASENFE

 WHERE 1=1 AND 2=2 -- MFL_NFELOG.SEQNOTAFISCAL = 29498715
   AND MFL_NFELOG.SEQNOTAFISCAL = MLFV_BASENFE.SEQNOTAFISCAL
   AND TRUNC(DTALOG) >= SYSDATE - 10
   AND MLFV_BASENFE.STATUSNFE IN (1,99)
   AND MLFV_BASENFE.dtaemissao >= SYSDATE - 10
   AND DESCRICAO LIKE '%TA_TMP_RETORNO_NF_OPHOS%'

)

LOOP
  UPDATE MFL_DOCTOFISCAL X SET X.STATUSNFE = 4, NFEDTAENV = SYSDATE WHERE X.SEQNOTAFISCAL = T.SEQNOTAFISCAL AND X.STATUSNFE IN (1,99);
  UPDATE MLF_NOTAFISCAL  X SET X.STATUSNFE = 4, NFEDTAENV = SYSDATE WHERE X.SEQNOTAFISCAL = T.SEQNOTAFISCAL AND X.STATUSNFE IN (1,99);

  END LOOP;
  COMMIT;
  
END;
