-- Cargas

SELECT MLO_CARGARECEB.TIPCARGARECEB,
       MLO_CARGARECEB.STATUSCARGA,
       MLO_CARGARECEB.STATUSARMAZENAGEM,
       COUNT(1),
       MLO_PARAMRECEB.DESCTIPCARGARECEB
  FROM MLO_CARGARECEB, MLO_PARAMRECEB

 WHERE MLO_CARGARECEB.TIPCARGARECEB = MLO_PARAMRECEB.TIPCARGARECEB
   AND MLO_CARGARECEB.NROEMPRESA = MLO_PARAMRECEB.NROEMPRESA
   AND MLO_CARGARECEB.NROEMPRESA = '503'
   AND MLO_CARGARECEB.DTAHORGERACAO > SYSDATE - 1

 GROUP BY MLO_CARGARECEB.TIPCARGARECEB,
          MLO_PARAMRECEB.DESCTIPCARGARECEB,
          MLO_CARGARECEB.STATUSCARGA,
          MLO_CARGARECEB.STATUSARMAZENAGEM

 ORDER BY MLO_CARGARECEB.TIPCARGARECEB,
          MLO_CARGARECEB.STATUSCARGA,
          MLO_CARGARECEB.STATUSARMAZENAGEM

-- Altera Status da Carga
-- STATUSCARGA para L/LIBERADA
-- STATUSCONFERENCIA para F/FINALIZADA
       
SELECT X.NROCARGA, X.NROEMPRESA, X.STATUSCARGA, X.STATUSCONFERENCIA
  FROM CONSINCO.MLO_CARGARECEB X
 WHERE X.NROEMPRESA = 503
   AND X.DTAHORGERACAO > SYSDATE - 1
   AND NROCARGA = 2339203
       
       FOR UPDATE
