ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

-- Confere produto/emp com sugestao que nao foi atendida

SELECT *
  FROM CONSINCO.NAGT_UNOUS_ABASTECIMENTO XX
 WHERE TRUNC(DATA_EMISSAO) = TRUNC(SYSDATE)
       AND NRO_EMPRESA_ORIGEM = 507
       
       AND NOT EXISTS 
       
       (SELECT 1
          FROM MAC_GERCOMPRA X INNER JOIN MAC_GERCOMPRAITEM XI ON XI.SEQGERCOMPRA = X.SEQGERCOMPRA
         WHERE X.SEQGERCOMPRA = 322526 -- Lote Gerado
           AND QTDPEDIDA = XX.QTDE
           AND XI.SEQPRODUTO = XX.SEQPRODUTO
           AND XI.NROEMPRESA = XX.NRO_EMPRESA_DESTINO)
           
