-- Altera o PD que limpa a tela no módulo de Orçamento

UPDATE CONSINCO.GE_PARAMDINAMICO X SET VALOR = 'S' WHERE PARAMETRO = 'PERM_LIMPA_TELA_APOS_INSERCAO';

COMMIT;

SELECT * FROM CONSINCO.GE_PARAMDINAMICO X WHERE PARAMETRO = 'PERM_LIMPA_TELA_APOS_INSERCAO' 
