SELECT (SUM(F2.VLRORIGINAL) OVER (PARTITION BY F2.DTAEMISSAO))
AS VLRSOMADO, NRODOCUMENTO, SEQTITULO
FROM FI_TITULO F2;

--

ROW_NUMBER() OVER(PARTITION BY PCC.SEQPRODUTO ORDER BY PCC.SEQPRODUTO) ODR
