-- Ajustar o campo INDREGULAR da tabela CCT_CENARIOIMPOSTO de S pra N
-- Ticket 25023777 

BEGIN
  FOR VT IN (SELECT I.INDREGULAR,CCLAS.INDREGULAR INDREGULARCAD,I.SEQCENARIO, I.SEQCENARIOIMPOSTO
              FROM CCT_CENARIOIMPOSTO I,
                   CCT_CODIGOTRIBUTARIO CCLAS
             WHERE I.SEQCODTRIBCCLASTRIB = CCLAS.SEQCODIGOTRIBUTARIO (+)
               AND NVL(I.INDREGULAR,'N') != NVL(CCLAS.INDREGULAR,'N'))
  LOOP
    UPDATE CCT_CENARIOIMPOSTO I SET I.INDREGULAR = NVL(VT.INDREGULARCAD,'N') WHERE I.SEQCENARIOIMPOSTO = VT.SEQCENARIOIMPOSTO;
  END LOOP;               
  END;
