BEGIN
  
FOR t IN (SELECT NROEMPRESA FROM MAX_EMPRESA X)
  
    LOOP
      
    INSERT INTO NAGT_BASEVENDACESTA

SELECT /*+OPTIMIZER_FEATURES_ENABLE('11.2.0.4')*/
       MP.NROEMPRESA, P.SEQPRODUTO PLU_CESTA, P.DESCCOMPLETA, 
       ROUND(SUM(XI.QUANTIDADEPRODFINAL)/ 
      (SELECT COUNT(1) COMP FROM CONSINCO.MRLV_COMPONENTESRECEITA RC WHERE RC.SEQPRODUTOFINAL = P.SEQPRODUTO AND RC.NROEMPRESA = MP.NROEMPRESA)) QTD_CESTA_VENDIDA,
       CASE WHEN (MAX(MP.ESTQLOJA) - 
       ROUND(SUM(XI.QUANTIDADEPRODFINAL)/ 
      (SELECT COUNT(1) COMP FROM CONSINCO.MRLV_COMPONENTESRECEITA RC WHERE RC.SEQPRODUTOFINAL = P.SEQPRODUTO AND RC.NROEMPRESA = MP.NROEMPRESA))) < 0 THEN 0 ELSE
       MAX(MP.ESTQLOJA) - ROUND(SUM(XI.QUANTIDADEPRODFINAL)/ 
      (SELECT COUNT(1) COMP FROM CONSINCO.MRLV_COMPONENTESRECEITA RC WHERE RC.SEQPRODUTOFINAL = P.SEQPRODUTO AND RC.NROEMPRESA = MP.NROEMPRESA)) END ESTQ_LOJA_REAL
       
  FROM PDV_DOCTO X INNER JOIN PDV_DOCTOITEM XI ON X.SEQDOCTO = XI.SEQDOCTO
                   INNER JOIN MAP_PRODUTO P ON SUBSTR(P.SEQPRODUTO,2) = XI.SEQPRODUTOFINAL
                   INNER JOIN MRL_PRODUTOEMPRESA MP ON MP.NROEMPRESA = X.NROEMPRESA AND MP.SEQPRODUTO = P.SEQPRODUTO
                        
  WHERE X.DTAMOVIMENTO >= DATE '2024-11-01'
   AND P.INDPROCFABRICACAO = 'V'
   AND EXISTS (SELECT 1
                 FROM MAP_PRODUTO X 
                WHERE DESCCOMPLETA LIKE '%CESTA%NAT%ALIANZA%' 
                  AND SUBSTR(SEQPRODUTO,2) = XI.SEQPRODUTOFINAL)
                    
   AND X.NROEMPRESA = T.NROEMPRESA
                  
GROUP BY MP.NROEMPRESA, P.SEQPRODUTO, P.DESCCOMPLETA;

      COMMIT;
  END LOOP;

END;
