ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

SELECT SEQGERCOMPRA, NROEMPRESA, X.SEQPRODUTO, X.TFVLRCUSTOBASE, X.QTDPEDIDA,
       X.VLRUNITVERBA * QTDEMBALAGEM VERBA, X.TFVLRVERBABONIF

  FROM MAC_GERCOMPRAITEM X
 WHERE SEQGERCOMPRA = 311435
   AND TFVLRVERBABONIF > TFVLRCUSTOBASE
