ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;
/*
SELECT * FROM CONSINCO.MLO_LOTEINVFISICO;
SELECT * FROM CONSINCO.MLO_LOTEINVFISITEM;
SELECT * FROM CONSINCO.MLO_)
SELECT * FROM CONSINCO.MLO_ENDERECO;
SELECT * FROM CONSINCO.MLO_ENDERECOQTDE;
*/
SELECT DISTINCT CODDEPOSITANTE||'-'||A.NROEMPRESA DP_CD,
       A.SEQENDERECO,
       A.CODRUA,
       A.SEQPRODUTO,
       A.QTDATUAL,
       A.USUALTERACAO ULT_USUALT,
       A.DTAALTERACAO ULT_DTAALT,
       A.APLALTERACAO ULT_APLALT
       
  FROM CONSINCO.MLO_ENDERECO A INNER JOIN MLO_ENDERECOQTDE B   ON A.SEQENDERECO = B.SEQENDERECO
                                LEFT JOIN MLO_LOTEINVFISITEM C ON C.SEQENDERECO = A.SEQENDERECO
 WHERE CODDEPOSITANTE = 507
   AND 1=1 
   AND NOT EXISTS (SELECT 1
                     FROM CONSINCO.MLO_LOTEINVFISICO X INNER JOIN MLO_LOTEINVFISITEM XI ON X.SEQLOTE = XI.SEQLOTE
                    WHERE 2=2 -- USUGERACAO = 'GIGOMES' pq fiz em homolog pra testar
                      AND XI.SEQENDERECO = A.SEQENDERECO
                      AND TRUNC(X.DTAHORGERACAO) BETWEEN DATE '2024-11-20' AND DATE '2024-11-21') -- Datas em que foram gerados os lotes do inventario de novembro
                      
   ORDER BY QTDATUAL DESC
